
languge: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t  bnaven1/docker-react -f Dockerfile.dev . 

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker"
  env: "NavReactDocker-env"
  bucket-name: "elasticbeanstalk-eu-west-2-512047505278"
  bucket-path: "docker"
  on:
    branch: master
  access_key_id: $AWS_Access_Key
  secret_access_key: 
    secure: "$AWS_Secret_Key"
